### PR TITLE
Added Rajat profile

### PR DESCRIPTION
**Pull request by MeghanTalasila**

### CODE REVIEW

**Comment by jdamerow** [comment]
please add to index.html too

**Comment by MeghanTalasila** [comment]
Updated the rajat profile in index.html and removed sarvani.html file which is pulled from master branch.

**Comment by erickpeirson** [comment]
@MeghanTalasila Looks like there are some merge conflicts. Let us know if you need help resolving them.

**Comment by jdamerow** [comment]
@MeghanTalasila please resolve the conflicts

**Comment by MeghanTalasila** [comment]
@jdamerow this pull request is out of date. All my changes are merged into gh-pages from branch Meghana_new. I created a new pull request to merge into master.. 

I cannot able to delete the pull request. Could you please delete this pull request then I will delete the branch to avoid conflicts and go with branch Meghana_new

**Pull request closed without merging**
