### PR TITLE
Sarvani

### PR DESCRIPTION
**Pull request by sarvani11**
Updated Index

### CODE REVIEW

**Comment by erickpeirson** [comment]
@sarvani11 Looks like there are some merge conflicts; let us know if you need help resolving them. :-)

**Comment by jdamerow** [comment]
@sarvani11 please resolve the conflicts

**Comment by sarvani11** [comment]
Hello Julia,

I didn't do any activity on my got for this particular sprint.Rajat had
made the changes. Are the conflicts particular to my github account or with
out story/QUAD-58

Thanks,
Sarvani

**Comment by jdamerow** [comment]
@sarvani11 , there are still merge conflicts.

**Pull request closed without merging**
